export const DIET_GOALS = [
  { id: 'weight-loss', label: 'Weight Loss', icon: '⚖️' },
  { id: 'muscle-gain', label: 'Muscle Gain', icon: '💪' },
  { id: 'maintenance', label: 'Maintenance', icon: '🎯' },
  { id: 'diabetic', label: 'Diabetic-friendly', icon: '🩺' },
  { id: 'iron-rich', label: 'Iron-rich', icon: '🌿' },
]

export const MEAL_TYPES = ['Breakfast', 'Lunch', 'Dinner', 'Refreshers', 'Snack', 'Dessert']

export const CALORIE_GOALS = {
  'weight-loss': 1800,
  'muscle-gain': 2600,
  maintenance: 2200,
  diabetic: 1900,
  'iron-rich': 2100,
}

export const GOAL_PRIORITY_TAGS = {
  'weight-loss': ['Weight Loss', 'Low Calorie', 'High Fiber', 'Low Fat'],
  'muscle-gain': ['Muscle Gain', 'High Protein', 'Energy Dense'],
  maintenance: ['Maintenance', 'Balanced', 'Whole Food'],
  diabetic: ['Diabetic-safe', 'Low Sugar', 'Low GI', 'High Fiber'],
  'iron-rich': ['Iron-rich', 'Iron Boost', 'High Protein'],
}

const makeRecipe = ({
  id, name, mealType, calories, protein, carbs, fat, fiber, tags, time, servings = 1,
  ingredients, steps, beginnerTip, description
}) => ({
  id,
  name,
  mealType,
  description,
  calories,
  protein,
  carbs,
  fat,
  fiber,
  tags,
  time,
  servings,
  ingredients,
  steps,
  beginnerTip,
})

export const SAMPLE_MEALS = {
  Breakfast: [
    makeRecipe({
      id: 'b1',
      mealType: 'Breakfast',
      name: 'Masala Tofu Scramble with Spinach & Roti',
      description: 'Protein-rich Indian vegan breakfast.',
      calories: 420, protein: 28, carbs: 38, fat: 14, fiber: 6,
      tags: ['High Protein', 'Iron-rich', 'Muscle Gain'],
      time: '20 min',
      servings: 2,
      ingredients: ['200g firm tofu', '1 cup spinach', '1 onion', '1 tomato', '1/2 tsp turmeric', '1/2 tsp cumin seeds', '1 tsp oil', '2 rotis', 'Salt as needed'],
      steps: ['Crumble tofu with your hands.', 'Heat oil in a pan.', 'Add cumin and onion, cook 2 minutes.', 'Add tomato, turmeric, and salt.', 'Add tofu and spinach.', 'Cook 5 minutes.', 'Serve with warm roti.'],
      beginnerTip: 'Cook on medium flame so tofu stays soft.',
    }),
    makeRecipe({
      id: 'b2',
      mealType: 'Breakfast',
      name: 'Overnight Oats with Chia & Mango',
      description: 'No-cook fiber-rich breakfast.',
      calories: 380, protein: 12, carbs: 62, fat: 10, fiber: 9,
      tags: ['Weight Loss', 'High Fiber', 'Low Fat'],
      time: '5 min + overnight',
      ingredients: ['1/2 cup oats', '1 tbsp chia seeds', '3/4 cup oat milk', '1/2 cup mango', '1 tsp maple syrup'],
      steps: ['Add oats and chia to a jar.', 'Add oat milk and maple syrup.', 'Mix well.', 'Refrigerate overnight.', 'Top with mango before eating.'],
      beginnerTip: 'Add extra milk in the morning if it becomes too thick.',
    }),
    makeRecipe({
      id: 'b3',
      mealType: 'Breakfast',
      name: 'Peanut Butter Banana Smoothie Bowl',
      description: 'High-energy breakfast bowl.',
      calories: 450, protein: 18, carbs: 55, fat: 16, fiber: 7,
      tags: ['Muscle Gain', 'Energy Dense', 'High Protein'],
      time: '10 min',
      ingredients: ['1 frozen banana', '1 tbsp peanut butter', '1/2 cup soy milk', '2 tbsp granola', '1 tsp flaxseeds'],
      steps: ['Add banana, peanut butter, and soy milk to blender.', 'Blend until thick.', 'Pour into bowl.', 'Top with granola and flaxseeds.'],
      beginnerTip: 'Use frozen banana for thick texture.',
    }),
    makeRecipe({
      id: 'b4',
      mealType: 'Breakfast',
      name: 'Moong Dal Chilla with Mint Chutney',
      description: 'Indian protein-rich breakfast.',
      calories: 330, protein: 18, carbs: 42, fat: 8, fiber: 8,
      tags: ['Weight Loss', 'High Protein', 'Low Fat'],
      time: '25 min',
      ingredients: ['1/2 cup soaked moong dal', '1 green chilli', '1/2 tsp cumin', '1 tsp oil', 'Mint chutney', 'Salt'],
      steps: ['Blend soaked dal with chilli and cumin.', 'Add salt.', 'Heat pan and spread batter.', 'Cook both sides with little oil.', 'Serve with mint chutney.'],
      beginnerTip: 'Keep batter like dosa batter, not too thick.',
    }),
    makeRecipe({
      id: 'b5',
      mealType: 'Breakfast',
      name: 'Ragi Banana Porridge',
      description: 'Iron-rich warm breakfast.',
      calories: 310, protein: 8, carbs: 58, fat: 6, fiber: 7,
      tags: ['Iron-rich', 'Weight Loss', 'High Fiber'],
      time: '15 min',
      ingredients: ['3 tbsp ragi flour', '1 cup almond milk', '1 banana', '1 tsp jaggery', '1/4 tsp cardamom'],
      steps: ['Mix ragi flour with little water.', 'Heat almond milk.', 'Add ragi paste slowly.', 'Stir continuously.', 'Add mashed banana and cardamom.', 'Cook until thick.'],
      beginnerTip: 'Stir continuously to avoid lumps.',
    }),
    makeRecipe({
      id: 'b6',
      mealType: 'Breakfast',
      name: 'Sprouts Poha Bowl',
      description: 'Light Indian breakfast with sprouts.',
      calories: 350, protein: 14, carbs: 54, fat: 8, fiber: 8,
      tags: ['Maintenance', 'High Fiber', 'Whole Food'],
      time: '20 min',
      ingredients: ['1 cup poha', '1/2 cup sprouts', '1 onion', '1 tsp oil', 'Curry leaves', '1/2 tsp mustard seeds', 'Salt'],
      steps: ['Wash poha and keep aside.', 'Heat oil.', 'Add mustard seeds and curry leaves.', 'Add onion and cook.', 'Add sprouts and poha.', 'Mix and cook 3 minutes.'],
      beginnerTip: 'Do not soak poha too long or it becomes mushy.',
    }),
    makeRecipe({
      id: 'b7',
      mealType: 'Breakfast',
      name: 'Besan Vegetable Pancake',
      description: 'Quick vegan pancake.',
      calories: 360, protein: 16, carbs: 40, fat: 12, fiber: 6,
      tags: ['High Protein', 'Diabetic-safe', 'Low GI'],
      time: '20 min',
      ingredients: ['1/2 cup besan', '1/4 cup carrot', '1/4 cup capsicum', '1/2 tsp cumin', '1 tsp oil', 'Salt'],
      steps: ['Mix besan with water.', 'Add vegetables and spices.', 'Heat pan.', 'Spread batter.', 'Cook both sides until golden.'],
      beginnerTip: 'Make batter slightly thick for easy flipping.',
    }),
    makeRecipe({
      id: 'b8',
      mealType: 'Breakfast',
      name: 'Apple Cinnamon Oats',
      description: 'Warm low-sugar oats.',
      calories: 320, protein: 10, carbs: 56, fat: 7, fiber: 9,
      tags: ['Diabetic-safe', 'Low Sugar', 'High Fiber'],
      time: '12 min',
      ingredients: ['1/2 cup oats', '1 apple', '1 cup soy milk', '1/4 tsp cinnamon', '1 tsp chia seeds'],
      steps: ['Heat soy milk.', 'Add oats.', 'Cook 5 minutes.', 'Add chopped apple and cinnamon.', 'Top with chia seeds.'],
      beginnerTip: 'Use sweet apple instead of sugar.',
    }),
  ],

  Lunch: [
    makeRecipe({
      id: 'l1',
      mealType: 'Lunch',
      name: 'Chickpea Dal with Brown Rice & Cucumber Raita',
      description: 'Fiber-rich diabetic-friendly lunch.',
      calories: 510, protein: 22, carbs: 64, fat: 9, fiber: 14,
      tags: ['Diabetic-safe', 'High Fiber', 'Low GI'],
      time: '35 min',
      servings: 2,
      ingredients: ['1 cup cooked chickpeas', '1/2 cup brown rice', '1 onion', '1 tomato', '1/2 tsp turmeric', '1/2 cup coconut yogurt', '1/2 cucumber', 'Salt'],
      steps: ['Cook brown rice.', 'Heat oil in pan.', 'Cook onion and tomato.', 'Add spices and chickpeas.', 'Simmer 10 minutes.', 'Mix cucumber with coconut yogurt.', 'Serve dal with rice and raita.'],
      beginnerTip: 'Use cooked chickpeas to save time.',
    }),
    makeRecipe({
      id: 'l2',
      mealType: 'Lunch',
      name: 'Quinoa Veggie Bowl with Tahini Dressing',
      description: 'Balanced vegan lunch bowl.',
      calories: 480, protein: 19, carbs: 58, fat: 15, fiber: 11,
      tags: ['Maintenance', 'Balanced', 'High Protein'],
      time: '25 min',
      ingredients: ['1/2 cup quinoa', '1 cup water', '1 cup mixed vegetables', '1 tbsp tahini', '1 tsp lemon juice', 'Salt'],
      steps: ['Wash quinoa.', 'Cook quinoa with water.', 'Saute vegetables.', 'Mix tahini with lemon and water.', 'Add quinoa and vegetables to bowl.', 'Pour dressing.'],
      beginnerTip: 'Wash quinoa well to avoid bitter taste.',
    }),
    makeRecipe({
      id: 'l3',
      mealType: 'Lunch',
      name: 'Red Lentil Soup with Whole Wheat Bread',
      description: 'Iron-rich comforting lunch.',
      calories: 420, protein: 24, carbs: 56, fat: 7, fiber: 16,
      tags: ['Iron-rich', 'Low Fat', 'High Fiber'],
      time: '30 min',
      ingredients: ['1 cup red lentils', '1 tomato', '1 carrot', '3 garlic cloves', '4 cups water', '2 bread slices', 'Salt'],
      steps: ['Wash lentils.', 'Cook garlic and tomato.', 'Add carrot, lentils, water, and salt.', 'Boil 20 minutes.', 'Mash lightly.', 'Serve with bread.'],
      beginnerTip: 'Red lentils cook fast and do not need soaking.',
    }),
    makeRecipe({
      id: 'l4',
      mealType: 'Lunch',
      name: 'Rajma Brown Rice Bowl',
      description: 'High-fiber kidney bean lunch.',
      calories: 560, protein: 24, carbs: 78, fat: 10, fiber: 15,
      tags: ['Muscle Gain', 'High Protein', 'High Fiber'],
      time: '40 min',
      ingredients: ['1 cup cooked rajma', '1/2 cup brown rice', '1 onion', '1 tomato', '1 tsp rajma masala', 'Salt'],
      steps: ['Cook brown rice.', 'Cook onion and tomato.', 'Add rajma masala.', 'Add cooked rajma and water.', 'Simmer 15 minutes.', 'Serve with rice.'],
      beginnerTip: 'Use pressure-cooked rajma for soft texture.',
    }),
    makeRecipe({
      id: 'l5',
      mealType: 'Lunch',
      name: 'Millet Vegetable Khichdi',
      description: 'Light weight-loss lunch.',
      calories: 390, protein: 14, carbs: 62, fat: 8, fiber: 10,
      tags: ['Weight Loss', 'Low Fat', 'High Fiber'],
      time: '30 min',
      ingredients: ['1/2 cup millet', '1/4 cup moong dal', '1 cup vegetables', '1/2 tsp cumin', '1 tsp oil', 'Salt'],
      steps: ['Wash millet and dal.', 'Heat oil and cumin.', 'Add vegetables.', 'Add millet, dal, salt, and water.', 'Pressure cook 3 whistles.', 'Serve warm.'],
      beginnerTip: 'Add more water for soft khichdi.',
    }),
    makeRecipe({
      id: 'l6',
      mealType: 'Lunch',
      name: 'Tofu Buddha Bowl',
      description: 'Protein-rich lunch bowl.',
      calories: 520, protein: 30, carbs: 55, fat: 18, fiber: 9,
      tags: ['Muscle Gain', 'High Protein', 'Balanced'],
      time: '25 min',
      ingredients: ['200g tofu', '1/2 cup rice', '1 cup vegetables', '1 tsp soy sauce', '1 tsp sesame oil'],
      steps: ['Cook rice.', 'Cube tofu.', 'Saute tofu until golden.', 'Cook vegetables.', 'Add rice, tofu, and vegetables to bowl.', 'Add soy sauce.'],
      beginnerTip: 'Pat dry tofu before cooking for crisp texture.',
    }),
    makeRecipe({
      id: 'l7',
      mealType: 'Lunch',
      name: 'Palak Chana Bowl',
      description: 'Iron-rich spinach and chana bowl.',
      calories: 460, protein: 22, carbs: 52, fat: 12, fiber: 13,
      tags: ['Iron-rich', 'High Fiber', 'High Protein'],
      time: '30 min',
      ingredients: ['1 cup cooked chana', '2 cups spinach', '1 onion', '1 tomato', '1/2 tsp cumin', 'Salt'],
      steps: ['Blend spinach after boiling 1 minute.', 'Cook onion and tomato.', 'Add chana and spinach puree.', 'Simmer 8 minutes.', 'Serve warm.'],
      beginnerTip: 'Do not overboil spinach.',
    }),
    makeRecipe({
      id: 'l8',
      mealType: 'Lunch',
      name: 'Veggie Hummus Wrap',
      description: 'Easy balanced lunch wrap.',
      calories: 430, protein: 16, carbs: 55, fat: 14, fiber: 9,
      tags: ['Maintenance', 'Whole Food', 'Balanced'],
      time: '15 min',
      ingredients: ['2 whole wheat wraps', '4 tbsp hummus', '1/2 cup cucumber', '1/2 cup carrot', 'Lettuce', 'Salt'],
      steps: ['Warm wrap.', 'Spread hummus.', 'Add vegetables.', 'Sprinkle salt.', 'Roll tightly.', 'Cut and serve.'],
      beginnerTip: 'Do not overfill wrap or it will tear.',
    }),
  ],

  Dinner: [
    makeRecipe({
      id: 'd1',
      mealType: 'Dinner',
      name: 'Palak Tofu with Quinoa',
      description: 'Iron and protein-rich vegan dinner.',
      calories: 530, protein: 32, carbs: 48, fat: 16, fiber: 10,
      tags: ['Iron-rich', 'High Protein', 'Muscle Gain'],
      time: '35 min',
      ingredients: ['250g tofu', '3 cups spinach', '1/2 cup quinoa', '1 onion', '1 tomato', '3 garlic cloves', 'Salt'],
      steps: ['Cook quinoa.', 'Boil spinach 1 minute.', 'Blend spinach.', 'Cook onion, tomato, and garlic.', 'Add spinach paste.', 'Add tofu cubes.', 'Simmer and serve with quinoa.'],
      beginnerTip: 'Add tofu at the end to avoid breaking.',
    }),
    makeRecipe({
      id: 'd2',
      mealType: 'Dinner',
      name: 'Black Bean Tacos with Avocado Salsa',
      description: 'Fiber-rich Mexican vegan dinner.',
      calories: 490, protein: 20, carbs: 60, fat: 18, fiber: 13,
      tags: ['High Fiber', 'Balanced', 'Maintenance'],
      time: '20 min',
      ingredients: ['1 cup black beans', '4 corn tortillas', '1 avocado', '1 tomato', '1 onion', '1 tsp lemon juice', 'Salt'],
      steps: ['Cook beans with spices.', 'Mash slightly.', 'Mix avocado, tomato, onion, and lemon.', 'Warm tortillas.', 'Fill with beans and salsa.'],
      beginnerTip: 'Warm tortillas before filling.',
    }),
    makeRecipe({
      id: 'd3',
      mealType: 'Dinner',
      name: 'Thai Green Curry with Tempeh & Jasmine Rice',
      description: 'High-protein creamy vegan curry.',
      calories: 580, protein: 28, carbs: 66, fat: 20, fiber: 8,
      tags: ['Muscle Gain', 'Energy Dense', 'High Protein'],
      time: '35 min',
      ingredients: ['200g tempeh', '1 cup rice', '1 cup coconut milk', '1 tbsp green curry paste', '1 cup vegetables', 'Salt'],
      steps: ['Cook rice.', 'Heat curry paste.', 'Add coconut milk.', 'Add tempeh and vegetables.', 'Simmer 12 minutes.', 'Serve with rice.'],
      beginnerTip: 'Keep flame low after adding coconut milk.',
    }),
    makeRecipe({
      id: 'd4',
      mealType: 'Dinner',
      name: 'Vegetable Clear Soup with Tofu',
      description: 'Light low-calorie dinner.',
      calories: 260, protein: 16, carbs: 28, fat: 8, fiber: 6,
      tags: ['Weight Loss', 'Low Calorie', 'Low Fat'],
      time: '20 min',
      ingredients: ['100g tofu', '1 cup cabbage', '1/2 cup carrot', '1/2 cup beans', '3 cups water', 'Pepper', 'Salt'],
      steps: ['Boil water.', 'Add vegetables.', 'Cook 8 minutes.', 'Add tofu.', 'Add salt and pepper.', 'Serve hot.'],
      beginnerTip: 'Do not overcook vegetables.',
    }),
    makeRecipe({
      id: 'd5',
      mealType: 'Dinner',
      name: 'Stuffed Bell Peppers with Lentils',
      description: 'High-fiber dinner.',
      calories: 430, protein: 21, carbs: 52, fat: 12, fiber: 14,
      tags: ['Iron-rich', 'High Fiber', 'Diabetic-safe'],
      time: '40 min',
      ingredients: ['2 bell peppers', '1 cup cooked lentils', '1/2 cup rice', '1 tomato', 'Spices', 'Salt'],
      steps: ['Cut bell peppers.', 'Mix lentils, rice, tomato, and spices.', 'Fill peppers.', 'Bake or pan-cook until soft.', 'Serve warm.'],
      beginnerTip: 'Use cooked lentils to reduce time.',
    }),
    makeRecipe({
      id: 'd6',
      mealType: 'Dinner',
      name: 'Low-Cal Cauliflower Rice Bowl',
      description: 'Weight-loss friendly dinner.',
      calories: 300, protein: 12, carbs: 35, fat: 10, fiber: 10,
      tags: ['Weight Loss', 'Low Calorie', 'Low Fat'],
      time: '20 min',
      ingredients: ['2 cups grated cauliflower', '1 cup vegetables', '1 tsp oil', '1/2 tsp pepper', 'Salt'],
      steps: ['Grate cauliflower.', 'Heat oil.', 'Add vegetables.', 'Add cauliflower rice.', 'Cook 5 minutes.', 'Season and serve.'],
      beginnerTip: 'Do not add too much water.',
    }),
    makeRecipe({
      id: 'd7',
      mealType: 'Dinner',
      name: 'Soya Chunk Curry with Chapati',
      description: 'High-protein dinner.',
      calories: 560, protein: 34, carbs: 58, fat: 16, fiber: 8,
      tags: ['Muscle Gain', 'High Protein'],
      time: '30 min',
      ingredients: ['1 cup soya chunks', '1 onion', '1 tomato', '1 tsp curry powder', '2 chapatis', 'Salt'],
      steps: ['Boil soya chunks.', 'Squeeze water.', 'Cook onion and tomato.', 'Add spices and soya.', 'Simmer 10 minutes.', 'Serve with chapati.'],
      beginnerTip: 'Squeeze boiled soya chunks well to remove smell.',
    }),
    makeRecipe({
      id: 'd8',
      mealType: 'Dinner',
      name: 'Mushroom Millet Pulao',
      description: 'Balanced light dinner.',
      calories: 410, protein: 14, carbs: 60, fat: 12, fiber: 8,
      tags: ['Maintenance', 'Balanced', 'Whole Food'],
      time: '30 min',
      ingredients: ['1/2 cup millet', '1 cup mushrooms', '1 onion', '1 tsp oil', 'Whole spices', 'Salt'],
      steps: ['Wash millet.', 'Cook onion and mushrooms.', 'Add millet and water.', 'Cook until soft.', 'Serve hot.'],
      beginnerTip: 'Use 1.5 cups water for 1/2 cup millet.',
    }),
  ],

  Refreshers: [
    makeRecipe({
      id: 'r1',
      mealType: 'Refreshers',
      name: 'Mint Lemon Cucumber Cooler',
      description: 'Hydrating summer drink.',
      calories: 60, protein: 1, carbs: 14, fat: 0, fiber: 2,
      tags: ['Weight Loss', 'Low Calorie', 'Hydrating'],
      time: '5 min',
      ingredients: ['1 cup cucumber', '8 mint leaves', '1 tbsp lemon juice', '1 tsp chia seeds', '1 glass cold water'],
      steps: ['Wash cucumber and mint.', 'Add all ingredients to blender.', 'Blend 30 seconds.', 'Pour into glass.', 'Serve chilled.'],
      beginnerTip: 'Skip sweetener for weight loss.',
    }),
    makeRecipe({
      id: 'r2',
      mealType: 'Refreshers',
      name: 'Mango Coconut Vegan Smoothie',
      description: 'Creamy fruit smoothie.',
      calories: 190, protein: 3, carbs: 36, fat: 5, fiber: 4,
      tags: ['Maintenance', 'Energy Dense'],
      time: '7 min',
      ingredients: ['1/2 cup mango', '1/2 banana', '1 cup coconut milk', '1 tsp chia seeds', 'Ice cubes'],
      steps: ['Chop mango and banana.', 'Add everything to blender.', 'Blend smooth.', 'Serve chilled.'],
      beginnerTip: 'Use frozen mango for thick texture.',
    }),
    makeRecipe({
      id: 'r3',
      mealType: 'Refreshers',
      name: 'Watermelon Mint Refresher',
      description: 'Naturally sweet cooler.',
      calories: 75, protein: 1, carbs: 18, fat: 0, fiber: 1,
      tags: ['Weight Loss', 'Low Calorie', 'Hydrating'],
      time: '5 min',
      ingredients: ['2 cups watermelon', '6 mint leaves', '1 tsp lemon juice', 'Pinch black salt', 'Ice cubes'],
      steps: ['Remove seeds.', 'Blend watermelon, mint, lemon, and ice.', 'Pour into glass.', 'Serve immediately.'],
      beginnerTip: 'Do not add sugar.',
    }),
    makeRecipe({
      id: 'r4',
      mealType: 'Refreshers',
      name: 'Berry Soy Protein Smoothie',
      description: 'Protein-rich smoothie.',
      calories: 280, protein: 24, carbs: 32, fat: 7, fiber: 6,
      tags: ['Muscle Gain', 'High Protein'],
      time: '5 min',
      ingredients: ['1 cup soy milk', '1/2 cup berries', '1 banana', '1 tbsp peanut butter'],
      steps: ['Add all ingredients to blender.', 'Blend until creamy.', 'Pour into glass.', 'Serve cold.'],
      beginnerTip: 'Use chilled soy milk for better taste.',
    }),
    makeRecipe({
      id: 'r5',
      mealType: 'Refreshers',
      name: 'Amla Ginger Iron Booster',
      description: 'Iron-supporting refresher.',
      calories: 55, protein: 1, carbs: 12, fat: 0, fiber: 2,
      tags: ['Iron-rich', 'Iron Boost', 'Low Calorie'],
      time: '5 min',
      ingredients: ['1 amla', '1/2 inch ginger', '1 tsp lemon juice', '1 glass water', 'Pinch black salt'],
      steps: ['Chop amla.', 'Blend amla, ginger, and water.', 'Strain if needed.', 'Add lemon and salt.', 'Serve fresh.'],
      beginnerTip: 'Drink fresh because vitamin C reduces over time.',
    }),
    makeRecipe({
      id: 'r6',
      mealType: 'Refreshers',
      name: 'Coconut Lime Chia Drink',
      description: 'Cooling chia drink.',
      calories: 120, protein: 2, carbs: 18, fat: 4, fiber: 5,
      tags: ['Diabetic-safe', 'Low Sugar', 'Hydrating'],
      time: '10 min',
      ingredients: ['1 cup coconut water', '1 tbsp chia seeds', '1 tsp lime juice', 'Mint leaves'],
      steps: ['Soak chia in coconut water for 10 minutes.', 'Add lime juice.', 'Add mint.', 'Mix and serve.'],
      beginnerTip: 'Let chia swell before drinking.',
    }),
    makeRecipe({
      id: 'r7',
      mealType: 'Refreshers',
      name: 'Green Detox Spinach Smoothie',
      description: 'Green fiber-rich smoothie.',
      calories: 160, protein: 5, carbs: 30, fat: 3, fiber: 7,
      tags: ['Weight Loss', 'High Fiber', 'Low Fat'],
      time: '7 min',
      ingredients: ['1 cup spinach', '1/2 apple', '1/2 cucumber', '1 tsp lemon juice', '1 cup water'],
      steps: ['Wash spinach.', 'Chop apple and cucumber.', 'Blend all ingredients.', 'Serve fresh.'],
      beginnerTip: 'Start with less spinach if you are new to green smoothies.',
    }),
    makeRecipe({
      id: 'r8',
      mealType: 'Refreshers',
      name: 'Dates Almond Muscle Shake',
      description: 'High-calorie muscle gain drink.',
      calories: 360, protein: 14, carbs: 50, fat: 12, fiber: 6,
      tags: ['Muscle Gain', 'Energy Dense'],
      time: '5 min',
      ingredients: ['3 dates', '1 cup almond milk', '1 banana', '1 tbsp almond butter'],
      steps: ['Remove date seeds.', 'Add all ingredients to blender.', 'Blend until smooth.', 'Serve chilled.'],
      beginnerTip: 'Soak dates for 10 minutes if they are hard.',
    }),
  ],

  Snack: [
    makeRecipe({
      id: 's1',
      mealType: 'Snack',
      name: 'Roasted Chana & Mixed Nuts',
      description: 'Protein-rich crunchy snack.',
      calories: 180, protein: 9, carbs: 18, fat: 8, fiber: 5,
      tags: ['High Protein', 'Low Sugar'],
      time: '5 min',
      ingredients: ['1/4 cup roasted chana', '5 almonds', '5 cashews', '1 tbsp pumpkin seeds', 'Black pepper'],
      steps: ['Add all ingredients to bowl.', 'Sprinkle pepper.', 'Mix well.', 'Serve.'],
      beginnerTip: 'Limit nuts for weight loss.',
    }),
    makeRecipe({
      id: 's2',
      mealType: 'Snack',
      name: 'Apple with Almond Butter',
      description: 'Simple whole food snack.',
      calories: 200, protein: 5, carbs: 28, fat: 9, fiber: 4,
      tags: ['Maintenance', 'Whole Food'],
      time: '2 min',
      ingredients: ['1 apple', '1 tbsp almond butter', 'Cinnamon'],
      steps: ['Wash apple.', 'Slice apple.', 'Spread almond butter.', 'Sprinkle cinnamon.'],
      beginnerTip: 'Use only 1 tbsp almond butter.',
    }),
    makeRecipe({
      id: 's3',
      mealType: 'Snack',
      name: 'Cucumber Hummus Bites',
      description: 'Low-calorie snack.',
      calories: 140, protein: 6, carbs: 16, fat: 6, fiber: 5,
      tags: ['Weight Loss', 'Low Calorie'],
      time: '5 min',
      ingredients: ['1 cucumber', '3 tbsp hummus', 'Pepper', 'Chilli flakes'],
      steps: ['Slice cucumber.', 'Add hummus on each slice.', 'Sprinkle pepper.', 'Serve.'],
      beginnerTip: 'Keep cucumber slices thick.',
    }),
    makeRecipe({
      id: 's4',
      mealType: 'Snack',
      name: 'Soya Protein Cutlets',
      description: 'High-protein snack.',
      calories: 260, protein: 22, carbs: 24, fat: 8, fiber: 6,
      tags: ['Muscle Gain', 'High Protein'],
      time: '25 min',
      ingredients: ['1 cup soya granules', '1 boiled potato', 'Spices', '1 tsp oil', 'Salt'],
      steps: ['Soak soya granules.', 'Squeeze water.', 'Mix with potato and spices.', 'Shape cutlets.', 'Pan roast both sides.'],
      beginnerTip: 'Squeeze soya well before mixing.',
    }),
    makeRecipe({
      id: 's5',
      mealType: 'Snack',
      name: 'Sprouted Moong Salad',
      description: 'Fresh iron-rich snack.',
      calories: 170, protein: 11, carbs: 28, fat: 2, fiber: 7,
      tags: ['Iron-rich', 'High Fiber', 'Low Fat'],
      time: '10 min',
      ingredients: ['1 cup sprouts', '1 tomato', '1 onion', '1 tsp lemon juice', 'Salt'],
      steps: ['Wash sprouts.', 'Chop vegetables.', 'Mix sprouts and vegetables.', 'Add lemon and salt.', 'Serve fresh.'],
      beginnerTip: 'Use fresh sprouts only.',
    }),
    makeRecipe({
      id: 's6',
      mealType: 'Snack',
      name: 'Air-Fried Sweet Potato Fries',
      description: 'Healthy fiber-rich snack.',
      calories: 220, protein: 3, carbs: 42, fat: 5, fiber: 6,
      tags: ['Maintenance', 'High Fiber'],
      time: '25 min',
      ingredients: ['1 sweet potato', '1 tsp oil', 'Paprika', 'Salt'],
      steps: ['Cut sweet potato into sticks.', 'Mix with oil and spices.', 'Air fry 15–18 minutes.', 'Serve warm.'],
      beginnerTip: 'Cut equal-sized pieces for even cooking.',
    }),
  ],

  Dessert: [
    makeRecipe({
      id: 'de1',
      mealType: 'Dessert',
      name: 'Chia Pudding with Coconut & Berries',
      description: 'Healthy vegan dessert.',
      calories: 220, protein: 7, carbs: 28, fat: 10, fiber: 12,
      tags: ['High Fiber', 'Low Sugar', 'Diabetic-safe'],
      time: '5 min + 2 hr chill',
      ingredients: ['3 tbsp chia seeds', '1 cup coconut milk', '1 tsp maple syrup', '1/4 cup berries'],
      steps: ['Mix chia and coconut milk.', 'Add maple syrup.', 'Refrigerate 2 hours.', 'Top with berries.', 'Serve cold.'],
      beginnerTip: 'Stir once after 10 minutes to avoid lumps.',
    }),
    makeRecipe({
      id: 'de2',
      mealType: 'Dessert',
      name: 'Vegan Banana Nice Cream',
      description: 'Simple frozen banana dessert.',
      calories: 180, protein: 3, carbs: 38, fat: 2, fiber: 5,
      tags: ['Weight Loss', 'Low Fat'],
      time: '10 min',
      ingredients: ['2 frozen bananas', '1 tsp cocoa powder', '2 tbsp almond milk'],
      steps: ['Slice frozen bananas.', 'Add to blender.', 'Add cocoa and almond milk.', 'Blend creamy.', 'Serve immediately.'],
      beginnerTip: 'Use ripe bananas for sweetness.',
    }),
    makeRecipe({
      id: 'de3',
      mealType: 'Dessert',
      name: 'Dates Peanut Energy Balls',
      description: 'Energy-dense vegan dessert.',
      calories: 300, protein: 10, carbs: 38, fat: 14, fiber: 6,
      tags: ['Muscle Gain', 'Energy Dense'],
      time: '15 min',
      ingredients: ['6 dates', '2 tbsp peanuts', '1 tbsp oats', '1 tsp cocoa powder'],
      steps: ['Remove date seeds.', 'Blend dates, peanuts, oats, and cocoa.', 'Make small balls.', 'Refrigerate 10 minutes.'],
      beginnerTip: 'Wet your hands before rolling balls.',
    }),
    makeRecipe({
      id: 'de4',
      mealType: 'Dessert',
      name: 'Ragi Chocolate Pudding',
      description: 'Iron-rich vegan pudding.',
      calories: 240, protein: 6, carbs: 42, fat: 6, fiber: 5,
      tags: ['Iron-rich', 'Iron Boost'],
      time: '15 min',
      ingredients: ['3 tbsp ragi flour', '1 cup almond milk', '1 tsp cocoa', '1 tsp jaggery'],
      steps: ['Mix ragi with water.', 'Heat almond milk.', 'Add ragi paste.', 'Add cocoa and jaggery.', 'Stir until thick.'],
      beginnerTip: 'Add ragi slowly to avoid lumps.',
    }),
  ],
}

export const SUBSTITUTIONS = {
  'almond milk': ['oat milk', 'soy milk', 'coconut milk', 'cashew milk'],
  tofu: ['tempeh', 'chickpeas', 'seitan'],
  butter: ['coconut oil', 'vegan butter', 'avocado oil', 'olive oil'],
  eggs: ['flax eggs', 'chia eggs', 'aquafaba', 'silken tofu'],
  honey: ['maple syrup', 'agave nectar', 'date syrup', 'coconut nectar'],
  cheese: ['nutritional yeast', 'cashew cheese', 'vegan mozzarella'],
  cream: ['coconut cream', 'cashew cream', 'oat cream'],
  yogurt: ['coconut yogurt', 'soy yogurt', 'almond yogurt'],
}